// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkbwsukttbjsmvdxevzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrYndzdWt0dGJqc212ZHhldnp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcyMTYyOTAsImV4cCI6MjA4Mjc5MjI5MH0.Bg9ZdJAOwmtn6N4d7UP0fN9GGqJWZk2HApP8YIh7VAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);